from fastapi import APIRouter, HTTPException, Query

from app.models.object_graph import ExplorableObject, ObjectComponent, ObjectSearchResult
from app.services.object_library import ObjectLibrary


router = APIRouter(prefix="/api/objects", tags=["objects"])
object_library = ObjectLibrary()


@router.get("/search", response_model=list[ObjectSearchResult])
async def search_objects(q: str = Query(default="", description="Object or component search text")):
    return object_library.search(q)


@router.get("/{object_id}", response_model=ExplorableObject)
async def get_object(object_id: str):
    obj = object_library.get_object(object_id)
    if not obj:
        raise HTTPException(status_code=404, detail="Object not found")
    return obj


@router.get("/{object_id}/components/{component_id}", response_model=ObjectComponent)
async def get_component(object_id: str, component_id: str):
    component = object_library.get_component(object_id, component_id)
    if not component:
        raise HTTPException(status_code=404, detail="Component not found")
    return component


@router.post("/generate", response_model=ExplorableObject)
async def generate_object(q: str = Query(..., description="Object name to generate")):
    from main import ollama_service
    from app.agents.object_architect_agent import ObjectArchitectAgent
    
    if not ollama_service:
        # For testing fallback or direct CLI invocation where FastAPI startup hasn't run
        from app.services.ollama_service import OllamaService
        from app.config import get_settings
        settings = get_settings()
        ollama_service = OllamaService(
            host=settings.OLLAMA_HOST,
            model=settings.OLLAMA_MODEL,
            timeout=settings.OLLAMA_TIMEOUT
        )
        
    try:
        agent = ObjectArchitectAgent(ollama_service)
        obj = await agent.generate_object(q)
        return obj
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

from fastapi import UploadFile, File
from typing import List

@router.post("/generate-from-images", response_model=ExplorableObject)
async def generate_from_images(files: List[UploadFile] = File(...)):
    """Mock endpoint to handle 2D image to 3D GLB conversion"""
    # In a real scenario, this would send images to Luma AI, Tripo3D, or Meshy
    # and return a URL to a generated .glb file.
    
    # Returning a mock object utilizing the new GLTF geometry type
    return ExplorableObject(
        id="ai_generated_engine",
        name="AI Generated V8 Engine",
        type="mechanical_system",
        summary="Highly detailed 3D model generated from Google images via AI.",
        defaultView="assembled",
        model={"kind": "gltf", "assetUrl": "/assets/mock-engine.glb"},
        components=[
            ObjectComponent(
                id="main_body",
                name="Engine Main Body",
                parentId=None,
                scaleLevel="object",
                function="Main engine block and housing generated by AI.",
                material="Steel/Iron Composite",
                riskIfRemoved="System failure",
                position=[0, 0, 0],
                color="#ffffff",
                geometry={
                    "type": "gltf",
                    "url": "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/DamagedHelmet/glTF-Binary/DamagedHelmet.glb" # A fallback realistic model
                },
                children=[],
                microLevels=[]
            )
        ]
    )
